project_id = "ktmwnpiizdkzgxrzcaxd"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.track-usage]
verify_jwt = false
